		var cityIcon = L.icon({
		iconUrl: 'icons/CityIcon.png',
        shadowUrl: 'icons/Shadow.png',
        iconSize:     [40, 65],
        shadowSize:   [1, 1],
        iconAnchor:   [20, 64],
        shadowAnchor: [4, 62],
        popupAnchor:  [-3, -76]
		});


var el_qelged = L.marker([-49.461858,-7.373925,],{icon: cityIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/Qelged.jpg" alt="owo"style="width:700px;height:350px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Qelged</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">One of the original cities destroyed by Octavia due to their misuse of magic, Qelged sprawls thought the southern swamps of Quithar. The surrounding landscape sprouts massive roots that try to drag the ruin into the ground, though long abandoned arcane devices that were unable to be destroyed still fight back, continuing experiments and polluting the surrounding area with volatile magic. Even so, treasure hunters and explorers are drawn to it due to the winding tunnels and dungeons beneath the ground, still holding old coins and magical wonders.</p>'));
var el_mshHrt = L.marker([12.19023,24.216492,],{icon: cityIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/marshheart.jpg" alt="owo"style="width:700px;height:450px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Marsh-Heart</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">With foreboding towers perched upon high stone walls, Marsh-Heart is the bastion of humanity against the forces that exist in the swamps and wilderness. Steep roofed houses with stone foundations give superstitious citizens a safe place to rest will the military roams the surrounding farmlands. While Marsh-Heart is home to Sethmoors’ royal family, their roles have become obsolete as House Usis took up military control of the city and thus the province of Cradle. Public executions keep the populace confident that threats are dealt with, and the flow of monster hunters supply all manners of stories. Certain types of magic are prohibited in Marsh-Heart, with the sentence for dabbling in such magic being whatever flavour of death the gaolers have lined up for that week.</p>'));
var el_rvnNst = L.marker([45.645466,-43.211247,],{icon: cityIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/RavensNest.jpg" alt="owo"style="width:700px;height:450px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Ravens Nest</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">Hidden within a fetid grove, the shanty city of Ravens Nest is home to all manner of thieves, murderers, and occultists. While many people do make honest business here, many who find themselves living within the streets are individuals who dabble in dark magic, are cursed, or are involved in criminal activities. At the centre of this is the foul black stone tower that drips with black ooze. This citadel is home to Witch Queen Illanor, one of the three fey sisters. Here she consults her court of unseelie subjects to overtake vast swarths of the moorlands. The one rule in Ravens Nest is that all feuds are forgotten, as the city cannot afford to be torn apart from the inside out. Any other nicety is optional, though declining them is seen as poor manners.</p>'));
