        var factionIcon = L.icon({
		iconUrl: 'icons/FactionIcon.png',
        shadowUrl: 'icons/Shadow.png',
        iconSize:     [40, 65],
        shadowSize:   [1, 1],
        iconAnchor:   [20, 64],
        shadowAnchor: [4, 62],
        popupAnchor:  [-3, -76]
		});
var el_splicer = L.marker([2.019542, -75.914569,],{icon: factionIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/splicer.jpg" alt="owo"style="width:700px;height:425px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>The Splicers</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">While Sethmoor has its share of physicians, alchemists and other academics, Splicers are the mad scientists and inventors. No one officially endorses splicing, but no one opposes it either, so long as they keep to their expansive laboratories. There are three types of Splicers. The first are Ferrous Splicers. These individuals deal with prosthetics and machines, using rare materials to breath life into inorganic frames and successfully replace their own bodies. The second are Augmenter Splicers. These individuals are masters of biology, creating potions to alter ones body and grafts to attach animalistic upgrades onto already living things. Many Augmenters are some mix of plant, insect or reptile and humanoid. The last type are Flesh Splicers. These macabre doctors delve into the secrets of human flesh, creating all manners of zombies and horrors from corpses. Their necromantic dealings mean they are also skilled healers, and many have resorted to a Splicers knife to cure ailments.</p>'));
var el_thirassOrder = L.marker([22.945084, -65.950386,],{icon: factionIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/thirassOrder.jpg" alt="owo"style="width:425px;height:700px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>The Thirass Order</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">Stationed in a sunken fortress they call home, these willing humanoids have struck a blood pact with Lord Osyth the Blade of Thirass, a hateful, slain angelborn bound to an infernal blade. They fight with silver weapons and care little about humanity, their only interest involves putting the heads of undead, aberrations and demons on an iron pike. Their amour reflects their fighting style as well: light weight and mobile, so that they may better manoeuvre gear specially designed to kill otherworldly threats.</p>'));
var el_skybraceTalons = L.marker([-27.007145, -73.139419,],{icon: factionIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/skybraceTalon.jpg" alt="owo"style="width:600px;height:400px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>The Talons of Skybrace</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">The stalwart knights of Skybrace seem idealistic, however their perceived naivety is a facade to facilitate hope for those that are not strong enough to fend for themselves. They patrolling the boarder, flocks of them swoop from the skies to descend upon the threats that encroach on Orhelmic territory. They are purely humanity focused, and thus have bad relationships with the Fae that rule around them.</p>'));
var el_BFC = L.marker([51.45703, -7.970303,],{icon: factionIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/BFC.jpg" alt="owo"style="width:600px;height:400px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>The Black Fog Coalition</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">Peasantry that has been displaced, fugitives, disgraced soldiers and fearful commoners who have been shown no mercy from the powers in Sethmoor can look to the fractured by and find an answer: The Black Fog Coalition. The Coalition is a large band of lost souls that have cobbled together an efficient and cruel navy, pillaging and looting towns in raids of costal piracy. They fight for themselves, and any alure of ancient treasure is enough to send ships into the rivers beyond to find truths amongst rumours. They all congregate in the pirate capital of Caramo, though its location is heavily guarded by the fleet captains.</p>'));
var el_cathar = L.marker([21.881824, 18.625464,],{icon: factionIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/Cathars.jpg" alt="owo"style="width:300px;height:400px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>The Cathars</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">The Cathars are Sethmoors main militant force that spans from fresh foot soldiers to hardened veteran knights. Though they dress in the midnight black steel and chain that their saint wore, they are beacons of light; an unstoppable force to rundown that which dares step into humanities light. Any magic they wield is used to dispel darkness, inspire bravery, or cleanse the land of evil.</p>'));
var el_inquiz = L.marker([12.930405, 11.642897,],{icon: factionIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/inquisitor.jpg" alt="owo"style="width:300px;height:550px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>The Inquisitors</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">Following in the footsteps of St. Archibald, the Inquisitors are the elite investigators and secret police of Sethmoor. They can blend in seamlessly with a crowd, working quietly on cases and exploding into the houses of cultists, murderers, and the corrupt. The Inquisition works independently from the rest of the military, and even the heads of house Usis cannot overpower their practices.</p>'));
var el_WH = L.marker([3.706843, 14.631763,],{icon: factionIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/WH.jpg" alt="owo"style="width:500px;height:500px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>The Witch Hunters</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">To deal with magical threats, both monstrous and humanoid, house Usis sends out the Witch Hunters; individuals who train in negating, trapping and killing magic users and what they create. Using all manner of strange weapons, the Witch Hunters favour silvered bolts and weapons, and their armour is usually incomplete with their trademark pilgrim hat. Their magic is used to negate, disrupt, and kill.</p>'));
var el_SS = L.marker([24.304452, 31.646806,],{icon: factionIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/SquadSadist.jpg" alt="owo"style="width:600px;height:500px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Squadrus Sadistica</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">Where the Sadistic Squadron goes, only carnage follows. Heavy plates, fearless mounts, and with training only to kill in the most brutal way possible, a battalion of these knights have no tactics but the thrill of blood and breaking bones. Their magic destroys everything around them, as well as making sure they hit as hard as possible.</p>'));
var el_VigTho = L.marker([13.357136, -82.163043,],{icon: factionIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/VigTho.jpg" alt="owo"style="width:300px;height:500px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>The Vigourthorn Coven</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">Bones to roots and flesh to rot, the Vigourthorn Coven sees the depravity on humanities civilisation and realises that we too must soak the soil with blood. After all, we are born from dirt, and to dirt we shall return. Ritual sacrifice, gruesome rites and midnight prayers to ancient and unseen forces of nature can be witnessed around their alters. They frequently adorn themselves in bones, pelts and blood, summoning the forces they feed to crush all semblance of civilisation.</p>'));
var el_Guides = L.marker([17.413683, -7.149835,],{icon: factionIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/HallGui.jpg" alt="owo"style="width:400px;height:500px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>The Hallowed Guides</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">The wilderness is harsh, hungry and unforgiving. Those who were forsaken by traditional faiths had to fend for themselves. In time, these people found ways to appease the moorlands through practices customs and offerings. They found that they could act with nature to protect themselves for as long as they provided a symbiotic relationship. Naming themselves the Hallowed Guides, the witches of this coven are the kindest to the world at large, though still hold a resentment to those that would see themselves superior to nature itself.</p>'));
var el_ChildInk = L.marker([40.75836, -65.679567,],{icon: factionIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/childInk.jpg" alt="owo"style="width:350px;height:500px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>The Children of Ink</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">Every mage and scholar knows that knowledge is power, but to allow that knowledge to run through your very veins is one step too far. The Children of Ink does not care. For them, power is its own reward. They are arcanist and foul magic wielders who tattoo themselves with ancient scripture that enhances their magic, mind and body. While some of these tattoos are temporary, many are permanent, and elder Ink Callers look akin to walking spell books. Necromancy, guile, and forbidden knowledge are all callings for the Children, as nothing is off limits for them o pursue their own personal goals.</p>'));
var el_OraBeyo = L.marker([61.554021, 7.423321,],{icon: factionIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/OraBeyo.jpg" alt="owo"style="width:300px;height:500px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>The Oracles of the Beyond</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">There are forces that humanity should never witness, let alone know about. They are forces that can mould the very fabric of reality, or tear it apart. For some, the lure of what lies beyond the stars is too great, and the truth of the divine and insight to the universe is worth the sacrifice of sanity. These individuals form the Oracles of the Beyond, diviners that attempt to glimpse past the veil of Thent and to worlds unknown. Their willingness to share what they have learned frightens many, and their hidden archives are ringing with the ramblings of madmen and scribblings of the far gone, yet still, they persist in their pursuit to open their eyes.</p>'));
var el_ShadMech = L.marker([46.544142, 54.151211,],{icon: factionIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/MechCult.jpg" alt="owo"style="width:350px;height:500px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>The Shadowed Mechanists</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">There is a phenomenon known as the Splicers Whisper that many innovative and intelligent Ferrous Splicers experience. The majority of these Splicers know better than to converse with strange voices, but those weak of will listen. The voice explains that it is the Great Machine, a Splicer that has fully transcended the shackles of flesh. If they continue to listen, they are driven to obsession to prepare the people of Thent for The Return. This voice tells them how to build foul inventions, enacting horrific experiments on unsuspecting people to turn them into mindless creations of flesh and metal. Though they are few and their reputation a rumour, the Shadow Mechanists make their public statements very clear: join, or become oil for the Great Machine.</p>'));





