		var fortIcon = L.icon({
		iconUrl: 'icons/FortressIcon.png',
        shadowUrl: 'icons/Shadow.png',
        iconSize:     [40, 65],
        shadowSize:   [1, 1],
        iconAnchor:   [20, 64],
        shadowAnchor: [4, 62],
        popupAnchor:  [-3, -76]
		});


var el_miradorkeep = L.marker([-44.980551,-86.369508,],{icon: fortIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/miradorkeep.jpg" alt="owo"style="width:700px;height:400px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Mirador Keep</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">Built during the reign of the Elvish Tyranny, Mirador Keep is now a crumbling fortress with tunnels that run deep into the mountain and bisect ancient groves and valleys. Druidic settlements are nestled deep within the walls that pay homage to one of the old Faeries of Thent. Often one can see a druid from Mirador shaping the world around them, moving stone and shaping rivers for their granite lord, making sure the wilderness is on a constant, heathy state of flux.</p>'));

var el_skynest = L.marker([-27.017287,-74.445661,],{icon: fortIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/Skybrace.jpg" alt="owo"style="width:700px;height:450px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Skybrace Nest</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">The sprawling ruins of the Tethanar climbs the northernmost mountains of Orhelm. In the centre of this overgrown citadel is the reclaimed fortress of Skybrace. Located on the highest point of the ruins, the Skybrace nest is only accessible by wing. As such, the faction of knights that live and train their train on the back of griffons and hippogriffs, with giant birds being another common mount. Around the walls of the fortress is a secluded settlement for those refugees escaping Sethmoor, though the living conditions are tough, and horrors still stalk the decrepit and forgotten halls.</p>'));

var el_blightmoor = L.marker([14.277107,-40.120118,],{icon: fortIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/Blightmoor.jpg" alt="owo"style="width:700px;height:450px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Blightmoor</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">Upon twisted outcrops of copper-rich stone, the imposing and fuming fortress of Blightmoor sits. Home of the arrogant dragon Nitric, Blightmoor was once a great marble palace. During a grand ball, Nitric infiltrated the celebration in human form. When the time was right, he transformed, dissolving all around him with noxious breath. With the castles treasury claimed and surrounding hamlets prepopulated, Nitric demands absurd tithes to assure his subjects dont leave and have no resources to fight back.</p>'));

var el_radridal = L.marker([3.473744,-10.56039,],{icon: fortIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/Radridal.jpg" alt="owo"style="width:500px;height:600px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Radridal</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">The circular fortress town of Radridal is one of the most fortified settlement outside the Cradle. Citizens that live within the walls live quiet lives equal parts peaceful and paranoid. No one knows who rules their lands, who collects taxes from special bowls left in offertory plates, and where people go if they disobey the law. The only fact people know is that the tower of Radridal has no shortage of mute, plate-clad knights that answer to the Olzitaghar.</p>'));

var el_narakzig = L.marker([62.879563,-6.996526,],{icon: fortIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/narakzig.jpg" alt="owo"style="width:600px;height:600px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Narakzig</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">Twisting organic shapes and odd geometry make up the architecture of this sunken eldritch temple. No one knows how it got there or how it was built, though all who sleep around its mucus like waters have disturbing dreams that they are unable to recall upon awakening. Those that resist sleep and look to the temple recount colours that dance in odd and hypnotic forms with no discernible pattern.</p>'));

var el_irongate = L.marker([61.347618,63.467389,],{icon: fortIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/IronGate.jpg" alt="owo"style="width:700px;height:600px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Iron Gate</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">For years, Iron Gate was home to the most secure prison in Thent. The archmage of Sword Break and prison warden, Neselsia watched over the complex with its shifting halls, arcane guards and horrific traps. She was ageing, however, and the secrets of lichdom were at the forefront of her mind. When she finally ascended, Iron Gate prison became the largest soul harvesting facility, with Neselisas sentient phylactery being held in a central, heavily guarded panopticon. </p>'));



