		var greenIcon = L.icon({
		iconUrl: 'icons/OrhelmIcon.png',
        shadowUrl: 'icons/Shadow.png',
        iconSize:     [40, 65],
        shadowSize:   [1, 1],
        iconAnchor:   [20, 64],
        shadowAnchor: [4, 62],
        popupAnchor:  [-3, -76]
		});


var el_estenwatch = L.marker([-33.746913,-64.87791,],{icon: greenIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/Estenwatch.jpg" style="width:700px;height:450px"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Esternwatch</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">With high cobbled walls and sturdy yet simple towers, the central trade hub and border town of Orhelm and Sethmoor, Esternwatch, was established to connect the rural towns between the two realms. It is considered a neutral ground for all, with the politics of the fey courts and military views condoned, but not punished, by the guard of the Hold. Even though the town dislikes it, they are still upheld to the binding laws of Lady Octavia, and thus the is home to an Everautumn tree, a symbol of loyalty and a reminder that the fey Queen is always watching.</p>'));
var el_stredon = L.marker([2.147098, -70.839844,],{icon: greenIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/stredon.jpg" alt="owo"style="width:700px;height:400px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Stredon</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">Tucked away on the edge of a grand, dense forest, Stredons inhabitants live in the shadow of alchemy. The alchemists that live here brew all manner of toxins and remedies, often imbuing them with echoes of magic. This causes Stredon to stand on thin ice with House Usis, as though they dabble in darker magic, they are usually doing so to better humanity. Stredon is home to the Royal School of Pure and Applied Biology as a way to authenticate and monitor the learning of these practices, where people can donate their bodies for research if they need more money or medicine, which seems to be unnaturally present around Ochothas.</p>'));
var el_westbiens = L.marker([28.413549, -89.371514,],{icon: greenIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/westbiens.jpg" alt="owo"style="width:700px;height:450px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Westbeins</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">Where the borders of the swamp meet the dry plain of north-eastern Qualk, the swamp dries up, leaving cracked riverbeds and hidden aquifers that give rise to occasional sinkholes. Around the deepest aquifer is the town of Westbiens. The frontier town holds retired Witch hunters and mercenaries alike and being so detached from the Cradle means that the strict laws are more laxed. The town still has a large problem with demonic rifts opening in ground fissures, and so takes measures to prevent this.</p>'));
var el_londriande = L.marker([59.108892, -82.56498,],{icon: greenIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/londriande.jpg" alt="owo"style="width:700px;height:500px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Londriande</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">A cold and still air hangs around the crumbling town of Londriande. Solemn workers eek out a living hunting and gathering, as all crops end up wilting or frail. The houses and infrastructure is constantly rotting and is ever in a state of repair with hastily built walls and boarded windows. Many inhabitants take shelter in the old and repurposed access tunnels beneath the town that lead to the old church fortress that overlooks the town. When asked why they dont rebuild, many townsfolk say they dont have the resources, when in reality they know that it is a curse of rot and ruin that was planted in the old church centuries ago, lingering around inhabitants like a miasma.</p>'));
var el_icarset = L.marker([34.551426,-39.746453,],{icon: greenIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/icarset.jpg" alt="owo"style="width:650px;height:250px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Icarset</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">The heart of the black-market trade, Icarset is known as a necessary evil. The smugglers specialise in the trade of magical goods, metals and plants that are considered dangerous, and even forbidden knowledge, but never information on current events or rumours. Icarset has a longstanding relationship with Ravens Nest, as they allow the citys good to become more accessible to the population. No government is present, and the popular belief is that the town is run by the Oraqor Communion, though no one can find evidence to prove it.</p>'));
var el_graveset = L.marker([42.010733,-3.879822,],{icon: greenIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/graveset.jpg" alt="owo"style="width:600px;height:450px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Graveset</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">Currently the centre of maritime trade, Graveset deals with the most nautical traffic in the entire realm. Here, the local militia enforce a strict neutrality under the knowledge of destruction if a war between Ravens Nest and Marsh-Heart were to break out. As such, faith isnt talked about in public, and there are no public places of worship. The other concern for Graveset are the fleets of pirates that occasionally drift into the bays and ravage the coast. For this, Graveset has the most impressive display of black powder weaponry in Sethmoor.</p>'));
var el_inggrove = L.marker([30.765477,-10.323494,],{icon: greenIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/inggrove.jpg" alt="owo"style="width:600px;height:350px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Inggrove</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">Surrounded by a mangrove forest, the stilted town of Inggrove is secluded on a quiet peninsula. The town is walled all around, even in the port where thick stones dig deep into the waters. House Usis has an outpost here, a stronghold by the name Crux of Saint Mathe that holds the bones of the saint herself. As a result, the town is frequently assaulted by demons, devils and other horrors summoned from the forests beyond. The cultists that summon these seem to never drop in number, and the town has to ask for constant reinforcements from Cradle. Evacuations have been attempted in the past, but those escaping have always been found and massacred.</p>'));
var el_grullfeld = L.marker([37.948971,15.498586,],{icon: greenIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/grullfeld.jpg" alt="owo"style="width:600px;height:350px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Grullfeld</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">Grullfeld was the first true settlement to stand the test of time after the Era of Dragons, ruled by a line of paranoid, but benevolent, monarchs. Dark forces were held at bay for decades, until the reigning lady had twins. When she died under mysterious circumstances, the two siblings feuded over who would get the throne. When the conflict remained unresolved, they split to either side of the town, rallying people against the opposing sibling and against their fellow citizen with venomous propaganda. Now the town sits divided with a line of ruined and devastated buildings splitting the houses from each other. Now that a civil war has broken out, dark forces once more inhabit the shadows of that town, ready to play and influence the hands of the nobles..</p>'));
var el_matBal = L.marker([22.0851,17.630683,],{icon: greenIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/Mathbale.jpg" alt="owo"style="width:350px;height:500px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Mathes Balefire</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">The first beacon is hosted withing the walls of a grand citadel with houses built into the walls. Standing on the peak of a rocky outcrop, the beacon roars a holy yellow, and on cloudy days, the symbol of house Usis paints the sky.</p>'));
var el_arcLan = L.marker([13.022,10.523688,],{icon: greenIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/archlan.jpg" alt="owo"style="width:350px;height:500px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Archibalds Lantern</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">The second beacon glows a soft orange, though its light cuts through physical obscurities, showing the true form of what lurks within. The town has no walls, counting on the divine lanterns that deter all but the boldest of beasts.</p>'));
var el_edPha = L.marker([3.946268,13.603385,],{icon: greenIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/edupha.jpg" alt="owo"style="width:500px;height:350px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Edusas Pharos</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">The third of the beacons, Edusas Pharos is a strongly build fortress town etched with wards. Here, the historic archives of the Witch hunters lies deep beneath the town, holding all manner of historic artefacts and magic. This Beacons burns bright blue.</p>'));
var el_litchsor = L.marker([58.133752,-36.893269,],{icon: greenIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/litchsor.jpg" alt="owo"style="width:450px;height:650px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Litchsor</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">The large town of Litchsor is composed of three smaller settlements separated by rocky terrain. Here, no one volunteers for guard work. That role is taken by the ranks of undead risen to fulfill the wishes of the immortal ruler Hrethic, nothing more than bodies and mouthpieces to enforce martial law. The wraith of Cantrell was thought dead, but the hatred that spilt from him revived him full of avarice. Now the town of three parts suffers from the tyrants grudge, the reasons for which no one knows.</p>'));
var el_mournvale = L.marker([51.97564,29.751075,],{icon: greenIcon}).bindPopup(L.popup({maxWidth:1000}).setContent('<center><img src="usedImages/mournvale.jpg" alt="owo"style="width:700px;height:475px;"></center><br><p style="font-family:Perpetua Titling MT; font-size:40px; text-align:center"><b>Mournvale</b></p><hr><p style="font-family:Baskerville Old Face; font-size:20px">The quiet town of Mournvale is the largest settlement on the island of Draygrave. It was once the centre on maritime trade in the Era of Power, sporting many docks and bazaars where coin flowed freely. What they forgot were the fey that let them live there, and as more and more coin were collected, the more the races of humanity forgot the old rites and traditions of the fey. The Faeries grew spiteful, and in a slighted wrath they descended from the woodlands and massacred as many souls as possible. Now Mournvale hosts the largest graveyard in Thent, patrolled by resentful fey spirits who haunt the scarecrows, trees, and even rouse the dead.</p>'));
